name: Tortured Earth
favicon: null
layout_spectrum: 0
typography_spectrum: 0.10734
title: Tortured Earth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#741500'
    - '#c4c5ca'
    - '#c14e4d'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
