name: Tortured Earth
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26841976516880095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#741500'
    - '#c4c5ca'
    - '#c14e4d'
  brandStrength: 0.7922719230409712
  lightness: 0.16690773097798228
  saturation: 0.996214198647067
  rhythmicContrast: 0.6193892012815922
purpose: []
